server.port=8085

app.base-url=http://localhost:8085
app.name=PapeleriaApp
app.jwt.secret=MiClaveSecretaSuperSeguraParaJWT2024ConMasDe256BitsDeLongitud1234567890
app.jwt.expiration=86400000

spring.datasource.url=jdbc:mysql://localhost:3306/papeleria_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.web.resources.static-locations=classpath:/static/

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true

pos.printer.name=POS-58

logging.level.org.springframework.security=INFO
logging.level.com.papeleria.security=DEBUG
